### ISSUE TITLE
add sram block

### ISSUE THREAD

**Issue by mattvenn** [mattvenn/multi_project_tools#10]

**Comment by mattvenn** [comment]
we are documenting progress/ideas here https://docs.google.com/document/d/1-8AeNIIzsXWtidUxx8xsDvId14Mii2BdkWXOwrHh3jc/edit#

@embelon is working on this.

**Comment by mattvenn** [comment]
* install sram instructions: export SRAM_INSTALL=yes ; make pdk
* add sram instantce to uprj_netlist
* add sram to macro
* add block layer around sram macro
* instantiate and connect the sram in user_project_wrapper - needs extra wires
* add openram port to the shim instance

**Comment by mattvenn** [comment]
still needs to be accessible to the other projects.

we already have the openram definition in projects.yaml->interfaces

also missing from wrapper.v template. Update for MPW4 need to add this.

Then the wires need to be connected:

* disconnect wb shim from picorv32 wishbone
* if a project specifies 'openram' interface, then wire it up

**Comment by mattvenn** [comment]
Matt's suggestion

pros: simple
cons: caravel can't write to ram, so user project would have to provide an arbiter 

![mpw3 and mpw4 sram ideas](https://user-images.githubusercontent.com/634220/145549193-ef22e72c-9360-4c70-b4b2-0dd11c6fcb85.jpg)

**Comment by mattvenn** [comment]
Pawel's suggestion:

pros: caravel can write directly to sram
cons: more complex

![image](https://user-images.githubusercontent.com/634220/145549404-db364f1e-48c5-430a-b4ce-76dc58d016af.png)

**Comment by mattvenn** [comment]
qs from Urish

1. What does the address space for the SRAM WB bus look like?
  * from caravel, upper 1 k. we can do what we want. this address will be set in the shim (see pic above)

2. What's the width of the SRAM data / address wires? (SRAM 1k is organised 32x256)
   * 32 bit data, 
   * 8 bit address
3. What's the minimum write width?
   * we have a mask, so can write 1 byte

other qs

1. how long does it take to read and write
  * read is 2 cycles, write 2 cycles (maybe 3 - we need to check)

**Comment by mattvenn** [comment]
**left to be done for MPW4**

* Pawel finish dual port shim and test it
* Pawel to do the arbiter mux and test it 
* Matt to document the design
* Matt to provide an example pattern generator
   * wishbone registers for period (cycles), starting address
   * wishbone register for start/stop
   * reads 4x8 bit values from memory and puts them one at a time on the gpio
   * and provide a testbench with caravel firmware

**left to be done for future**

* clock domain crossing. At the moment the designs would need to use the same clock as caravel management

**Comment by urish** [comment]
> from caravel, upper 1 k. we can do what we want. this address will be set in the shim (see pic above)

From our projects too?
