### ISSUE TITLE
OpenLane with OpenRAM

### ISSUE THREAD

**Issue by mousaq92** [mattvenn/multi_project_tools#41]
Hello,

I am currently seeing DRC violations with an OpenLane design that has OpenRAM macros. Is this normal? What can I do to fix this?

Thanks,

Mousa

**Comment by mattvenn** [comment]
Hi Mousaq! sorry I didn't see this till now. We are using obstructions to help solve this. Check my MPW6 submission out for details: https://github.com/mattvenn/zero_to_asic_MPW6
